### ISSUE TITLE
Fase Implementação: Classe UserService

### ISSUE THREAD

**Issue by marleiSilveira** [codenation-dev/squad-2-ad-java-contaazul-1#17]

**Comment by KarinaApSouza2512** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fase Implementação : User](https://trello.com/c/P9HVLQSu/31-fase-implementa%C3%A7%C3%A3o-user)

**Comment by KarinaApSouza2512** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fase Implementação : User](https://trello.com/c/P9HVLQSu/31-fase-implementa%C3%A7%C3%A3o-user)

**Comment by KarinaApSouza2512** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service > UserService](https://trello.com/c/Dnbn5rs5/53-service-userservice)
