### ISSUE TITLE
Fase Implementação: Classe UserRepository

### ISSUE THREAD

**Issue by marleiSilveira** [codenation-dev/squad-2-ad-java-contaazul-1#18]

**Comment by aliceborges** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fase Implementação : User](https://trello.com/c/ghFhgx9o/32-fase-implementa%C3%A7%C3%A3o-user)

**Comment by KarinaApSouza2512** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fase Implementação : User](https://trello.com/c/P9HVLQSu/31-fase-implementa%C3%A7%C3%A3o-user)
