### ISSUE TITLE
Testes Automatizados - Log Service (parte 2)

### ISSUE THREAD

**Issue by aliceborges** [codenation-dev/squad-2-ad-java-contaazul-1#61]

**Comment by nataliasuzuki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testes Automatizados - Log Service (parte 1)](https://trello.com/c/qh2ONi4n/100-testes-automatizados-log-service-parte-1)

**Comment by aliceborges** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testes Automatizados - Log Service (parte 2)](https://trello.com/c/QFZYvdKt/101-testes-automatizados-log-service-parte-2)
